### ISSUE TITLE
Bug in Pairwise alignment

### ISSUE THREAD

**Issue by wsyyc** [rajewsky-lab/openst#60]
Hi, 
    When I was reproducing the E13 mouse head data according to the documentation, I encountered a bug during the 'Merging data modalities' step in the 'Pairwise alignment' section. The error message is as follows:
```
Traceback (most recent call last):
  File "/public1/yuchen/software/miniconda3/envs/spacemake/bin/openst", line 8, in <module>
    sys.exit(run_openst())
  File "/public1/yuchen/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/__main__.py", line 11, in run_openst
    cmdline_main()
  File "/public1/yuchen/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/cli.py", line 1547, in cmdline_main
    args.func(from_spacemake_parser, args, unknown_args)
  File "/public1/yuchen/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/cli.py", line 1433, in cmd_run_from_spacemake
    _run_from_spacemake(parser, args, unknown_args)
  File "/public1/yuchen/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/utils/from_spacemake.py", line 348, in _run_from_spacemake
    required_arguments = SUBPARSER_ACTIONS[subcommand](sample_config, sample_metadata)
  File "/public1/yuchen/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/utils/from_spacemake.py", line 255, in _run_merge_modalities
    stitched_dge = get_stitched_dge(sample_config, sample_metadata, check_exists=True)
  File "/public1/yuchen/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/utils/from_spacemake.py", line 178, in get_stitched_dge
    check_file_exists(_file, exception=check_exists)
  File "/public1/yuchen/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/utils/file.py", line 51, in check_file_exists
    raise FileNotFoundError(f"The file '{f}' does not exist.")
FileNotFoundError: The file 'projects/openst_demo/processed_data/openst_demo_e13_mouse_head/illumina/complete_data/dge/dge.all.polyA_adapter_trimmed.mm_included.spatial_beads_puck_collection.h5ad' does not exist.

```
    How should I resolve this issue?
Thank you!

**Comment by nukappa** [comment]
Hi @wsyyc, this doesn't seem like a bug, but that you miss the file `dge.all.polyA_adapter_trimmed.mm_included.spatial_beads_puck_collection.h5ad`. 

This is a unified `h5ad` file containing all tiles, see [here](https://rajewsky-lab.github.io/openst/latest/computational/pairwise_alignment/#tissue-transcriptome) how to create it with the `spatial_stitch` command.

**Comment by wsyyc** [comment]
Thank you!  I will try it.
