### ISSUE TITLE
Which version of pandas should I use?

### ISSUE THREAD

**Issue by QuinceyLv** [rajewsky-lab/openst#66]
## Describe the bug
rule create_qc_sheet:
    input: projects/visium_demo/processed_data/Mouse_Brain_Rep1/illumina/complete_data/star.Log.final.out, projects/visium_demo/processed_data/Mouse_Brain_Rep1/illumina/complete_data/split_reads.polyA_adapter_trimmed/read_type_num.txt, projects/visium_demo/processed_data/Mouse_Brain_Rep1/illumina/complete_data/split_reads.polyA_adapter_trimmed/strand_type_num.txt, projects/visium_demo/processed_data/Mouse_Brain_Rep1/illumina/complete_data/dge/dge.exon.polyA_adapter_trimmed.mm_included.10000_beads_no_spatial_data.obs.csv, projects/visium_demo/processed_data/Mouse_Brain_Rep1/illumina/complete_data/parsed_ribo_depletion_log.txt
    output: projects/visium_demo/processed_data/Mouse_Brain_Rep1/illumina/complete_data/qc_sheets/qc_sheet_Mouse_Brain_Rep1_no_spatial_data.html
    jobid: 61
    wildcards: project_id=visium_demo, sample_id=Mouse_Brain_Rep1, data_root_type=complete_data, downsampling_percentage=, puck_barcode_file_id_qc=no_spatial_data

Traceback (most recent call last):
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/dask/dataframe/__init__.py", line 52, in <module>
    from dask.dataframe import backends, dispatch, methods, rolling
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/dask/dataframe/backends.py", line 14, in <module>
    from dask.dataframe._compat import PANDAS_GE_220, is_any_real_numeric_dtype
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/dask/dataframe/_compat.py", line 9, in <module>
    import_optional_dependency("pandas")
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/dask/_compatibility.py", line 139, in import_optional_dependency
    raise ImportError(msg)
ImportError: Dask requires version '2.0.0' or newer of 'pandas' (version '1.5.1' currently installed).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/TJPROJ5/SC/projects_spatial_2024/openst_test_20240924/result/spacemake_20241009/.snakemake/scripts/tmpiq6xf9k4.automated_analysis.py", line 8, in <module>
    import squidpy as sq
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/squidpy/__init__.py", line 3, in <module>
    from squidpy import datasets, gr, im, pl, read, tl
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/squidpy/gr/__init__.py", line 2, in <module>
    from squidpy.gr._build import spatial_neighbors
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/squidpy/gr/_build.py", line 24, in <module>
    from spatialdata import SpatialData
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/spatialdata/__init__.py", line 6, in <module>
    import dask.dataframe as dd
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/dask/dataframe/__init__.py", line 122, in <module>
    raise ImportError(msg) from e
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install

## Steps to reproduce the bug
```sh
spacemake run
```

## Expected results
A successful run.

## Actual results
Error when running create_qc_sheet. 

## Environment info
- Platform: Linux
- Python version: 3.10

## Description
I was running openst pipeline using 10x visium data (https://www.10xgenomics.com/datasets/mouse-brain-coronal-section-1-ffpe-2-standard).
According to https://raw.githubusercontent.com/rajewsky-lab/spacemake/master/environment.yaml , I installed pandas=1.5.1, but Dask requires version '2.0.0' or newer of 'pandas' (version '1.5.1' currently installed). 
After upgrade pandas to 2.2.3:
rule run_automated_analysis:
    input: projects/visium_demo/processed_data/Mouse_Brain_Rep2/illumina/complete_data/dge/dge.exon.polyA_adapter_trimmed.mm_included.spatial_beads_visium.h5ad
    output: projects/visium_demo/processed_data/Mouse_Brain_Rep2/illumina/complete_data/automated_analysis/visium/umi_cutoff_1000/Mouse_Brain_Rep2_visium_results.h5ad
    jobid: 53
    wildcards: project_id=visium_demo, sample_id=Mouse_Brain_Rep2, data_root_type=complete_data, downsampling_percentage=, run_mode=visium, umi_cutoff=1000, puck_barcode_file_id_qc=visium

/fakepath/software/miniconda3/envs/spacemake/bin/python3.10 /fakepath/openst_test_20240924/result/spacemake_20241009/.snakemake/scripts/tmp0tlrvlkt.automated_analysis.py
/fakepath/software/miniconda3/envs/spacemake/bin/python3.10 /fakepath/openst_test_20240924/result/spacemake_20241009/.snakemake/scripts/tmpgz4vjwz2.automated_analysis.py
/fakepath/software/miniconda3/envs/spacemake/bin/python3.10 /fakepath/openst_test_20240924/result/spacemake_20241009/.snakemake/scripts/tmp_oihazuf.automated_analysis.py
/fakepath/software/miniconda3/envs/spacemake/bin/python3.10 /fakepath/openst_test_20240924/result/spacemake_20241009/.snakemake/scripts/tmpr40llbum.automated_analysis.py
Traceback (most recent call last):
  File "/fakepath/openst_test_20240924/result/spacemake_20241009/.snakemake/scripts/tmpgz4vjwz2.automated_analysis.py", line 19, in <module>
    adata = detect_tissue(adata, umi_cutoff)
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/spacemake/spatial/util.py", line 139, in detect_tissue
    tissue_islands = np.delete(islands, np.argmax(island_sizes))
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/numpy/lib/function_base.py", line 5245, in delete
    arr = asarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (335,) + inhomogeneous part.
Traceback (most recent call last):
  File "/fakepath/openst_test_20240924/result/spacemake_20241009/.snakemake/scripts/tmpr40llbum.automated_analysis.py", line 19, in <module>
    adata = detect_tissue(adata, umi_cutoff)
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/spacemake/spatial/util.py", line 139, in detect_tissue
    tissue_islands = np.delete(islands, np.argmax(island_sizes))
  File "/fakepath/software/miniconda3/envs/spacemake/lib/python3.10/site-packages/numpy/lib/function_base.py", line 5245, in delete
    arr = asarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (212,) + inhomogeneous part.

I'm not sure whether this was caused by pandas. 
Looking forward to your reply.

**Comment by danilexn** [comment]
Hi!

A bugfix to this issue will be deployed to master soon. 

In the meantime, you need to have:

- pandas==1.5.1 (or any other compatible with our environment.yaml) and

- dask==2022.11.0. 

Also, you might need to manually append project_id,sample_id, to the beginning of the project_df header, which is likely empty now – by default, index column names are written in older pandas, while it is not written in newer pandas.
The former is required for spacemake to work properly.

Hope this helps!
Dani

PS: for spacemake-related bugs, please check the rajewsky-lab/spacemake repo, there you might find a solution to common issues next time 😊.

**Comment by QuinceyLv** [comment]
> Hi!
> 
> A bugfix to this issue will be deployed to master soon.
> 
> In the meantime, you need to have:
> 
> * pandas==1.5.1 (or any other compatible with our environment.yaml) and
> * dask==2022.11.0.
> 
> Also, you might need to manually append project_id,sample_id, to the beginning of the project_df header, which is likely empty now – by default, index column names are written in older pandas, while it is not written in newer pandas. The former is required for spacemake to work properly.
> 
> Hope this helps! Dani
> 
> PS: for spacemake-related bugs, please check the rajewsky-lab/spacemake repo, there you might find a solution to common issues next time 😊.

Thanks for help~
