### ISSUE TITLE
KeyError: 'x_offset' when running spatial_stitch

### ISSUE THREAD

**Issue by QuinceyLv** [rajewsky-lab/openst#70]
## Describe the bug
I have made a sucessful spacemake run on visium samples, and I ran into this error when running open-st from_spacemake:

INFO 2024-10-30 17:33:36,482 - openst from_spacemake - running from spacemake directory
INFO 2024-10-30 17:33:36,482 - {'subcommand': 'from_spacemake', 'project_id': 'visium_demo', 'sample_id': 'DSG_Treat', 'run_mode': '', 'func': <function cmd_run_from_spacemake at 0x2b21f4b4ec20>}
INFO 2024-10-30 17:33:38,211 - openst spatial_stitch - running with the following parameters:
INFO 2024-10-30 17:33:38,211 - {'project_id': 'visium_demo', 'sample_id': 'DSG_Treat', 'run_mode': '', 'subcommand': 'spatial_stitch', 'tiles': ['projects/visium_demo/processed_data/DSG_Treat/illumina/complete_data/dge/dge.exon.polyA_adapter_trimmed.mm_included.spatial_beads_visium.h5ad'], 'tile_coordinates': '/TJPROJ5/SC/projects_spatial_2024/openst_test_20240924/result/spacemake_20241021/puck_data/visium_barcode_positions.csv', 'tile_id': ['visium'], 'tile_id_regex': '(L[1-4][a-b]_tile_[1-2][0-7][0-9][0-9])', 'h5_out': 'projects/visium_demo/processed_data/DSG_Treat/illumina/complete_data/dge/dge.exon.polyA_adapter_trimmed.mm_included.spatial_beads_puck_collection.h5ad', 'tile_id_key': 'tile_id', 'merge_output': 'same', 'join_output': 'outer', 'no_reset_index': False, 'no_transform': False, 'metadata': '', 'func': <function cmd_run_spatial_stitch at 0x2b21f4b4d990>}
INFO 2024-10-30 17:35:07,591 - Loading 1 tiles, correcting coordinates and merging
1it [00:21, 21.33s/it]
Traceback (most recent call last):
  File "/fakepath/miniconda3/envs/spacemake/bin/openst", line 8, in <module>
    sys.exit(run_openst())
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/__main__.py", line 11, in run_openst
    cmdline_main()
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/cli.py", line 1583, in cmdline_main
    args.func(from_spacemake_parser, args, unknown_args)
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/cli.py", line 1468, in cmd_run_from_spacemake
    _run_from_spacemake(parser, args, unknown_args)
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/utils/from_spacemake.py", line 353, in _run_from_spacemake
    args.func(args)
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/cli.py", line 674, in cmd_run_spatial_stitch
    _run_spatial_stitch(args)
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/preprocessing/spatial_stitch.py", line 239, in _run_spatial_stitch
    spatial_stitch = merge_tiles_to_collection(
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/preprocessing/spatial_stitch.py", line 214, in merge_tiles_to_collection
    spatial_stitch_list += [create_spatial_stitch(tile, tile_transform, ~no_reset_index, ~no_transform)]
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/preprocessing/spatial_stitch.py", line 64, in create_spatial_stitch
    tile = _transform_tile(tile, tile_transform)
  File "/fakepath/miniconda3/envs/spacemake/lib/python3.10/site-packages/openst/preprocessing/spatial_stitch.py", line 31, in _transform_tile
    x_ofs = tiles_transform["x_offset"][_tile_id]
KeyError: 'x_offset'

## Steps to reproduce the bug
```sh
openst from_spacemake \
	--project-id visium_demo \
	--sample-id DSG_Control \
	spatial_stitch \
	--tile-coordinates /fakepath/result/spacemake_20241021/puck_data/visium_barcode_positions.csv
```

## Environment info
- Platform: Linux
- Python version: 3.10.14
- open-st version: 0.2.2

**Comment by danilexn** [comment]
Hi! 

The `openst` package was primarily developed for data generated with the Open-ST protocol. Other technologies such as Seq-scope, Nova-ST and Stereo-seq might be compatible (we haven't tested, though), but Visium is probably not compatible with many steps of the `openst` package:

The reason for this error in `spatial_stitch` is that this command is meant to merge the different tiles from an Open-ST section into a single object (e.g., a section of 3x4 mm is composed of 3x4 tiles, that need to be stitched to the same coordinate system). For a similarly sized Visium (or Visium HD) section, there's a single tile.  Also, the `visium_barcode_positions.csv` file has a different structure than an Open-ST `coordinate_system`, which relates tile ID (not barcodes) to spatial offsets.

Therefore, this step is not necessary. If you are planning to run the pairwise alignment between imaging data and Visium,  `pairwise_aligner` should work, when you provide the `spacemake` output. We cannot guarantee that the `openst` tool is compatible with Visium data.

I hope this helps!

Best,
Dani
